# Build Stage
FROM node:20.20.0 AS builder

WORKDIR /app

# Copy CA certificates (if needed)
#COPY ./cert.crt /usr/local/share/ca-certificates/
#RUN update-ca-certificates
# Configure npm to use CA certificates
#RUN npm config set cafile /etc/ssl/certs/ca-certificates.crt
#ENV NODE_EXTRA_CA_CERTS=/app/cert.crt

# Copy package files and TypeScript config
COPY package*.json ./
COPY tsconfig.json ./

# Copy application source code
COPY . .

# Install all dependencies (including dev dependencies for TypeScript compilation)
RUN npm install

RUN export TEST_DATABASE_URL="postgresql://prisma:password@test-postgres:5432/test?schema=public"

# TODO add commands to generate and migrate
RUN npx prisma migrate dev --name init

RUN npx prisma generate

# Expose port
EXPOSE 3001

# Start the application
CMD ["sleep", "infinity"]