# Build Stage
FROM node:20.20.0 AS builder

WORKDIR /app

# Copy package files and TypeScript config
COPY package*.json ./
COPY tsconfig.json ./

# Install all dependencies (including dev dependencies for TypeScript compilation)
RUN npm install

# Copy application source code
COPY . .

# Expose port
EXPOSE 3001

# Start the application
CMD ["sleep", "infinity"]